#Kick starter pipeline for applications teams to get started with their AWS journey.

name: 'anl-kickstarter-$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  Disable_All_Stages: "yes"

trigger:
- master

stages:

- stage: stage1

  jobs:

  - job:  A
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: git --version
